// LLM API wrapper - uses MiniMax M2.7 API (OpenAI compatible)
import { config } from '../config';
import type { ChatMessage } from '../types';

const fetch = require('node-fetch');

interface LLMResponse {
  success: boolean;
  content: string;
  error?: string;
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

export async function callLLM(messages: ChatMessage[], maxTokens: number = 4096): Promise<LLMResponse> {
  if (!config.llmApiKey) {
    return { success: false, content: '', error: 'LLM API key not configured' };
  }

  try {
    console.log(`[LLM] Calling ${config.llmModel} at ${config.llmApiUrl}`);

    const response = await fetch(config.llmApiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.llmApiKey}`,
      },
      body: JSON.stringify({
        model: config.llmModel,
        messages,
        max_tokens: maxTokens,
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[LLM] API error:', response.status, errorText.slice(0, 200));
      return { success: false, content: '', error: `LLM API returned ${response.status}` };
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '';

    console.log(`[LLM] Success - generated ${content.length} characters`);
    return {
      success: true,
      content,
      usage: data.usage,
    };
  } catch (e: any) {
    console.error('[LLM] Request failed:', e.message);
    return { success: false, content: '', error: e.message };
  }
}

// AI service execution
export async function executeAIService(
  serviceId: string,
  systemPrompt: string,
  userPrompt: string
): Promise<LLMResponse> {
  const messages: ChatMessage[] = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  return callLLM(messages);
}

// Fallback for when LLM is unavailable - provides meaningful demo responses
export function getFallbackResponse(serviceId: string, prompt: string): string {
  const responses: Record<string, (p: string) => string> = {
    'ai-writer': (p) => `Generated by Claude Haiku 4.5 - Unable to process at this moment. Please try again. (Input: "${p.slice(0, 50)}...")`,
    'ai-translator': (p) => `Generated by Claude Haiku 4.5 - Translation service temporarily unavailable.`,
    'ai-coder': (p) => `Generated by Claude Haiku 4.5 - Code review service temporarily unavailable.`,
    'ai-analyst': (p) => `Generated by Claude Haiku 4.5 - Analysis service temporarily unavailable.`,
    'ai-summarizer': (p) => `Generated by Claude Haiku 4.5 - Summary service temporarily unavailable.`,
  };

  const handler = responses[serviceId] || responses['ai-writer'];
  return handler(prompt);
}
