// LLM API wrapper - compatible with OpenAI chat completions API
import { config } from '../config';
import type { ChatMessage } from '../types';

const fetch = require('node-fetch');

interface LLMResponse {
  success: boolean;
  content: string;
  error?: string;
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

export async function callLLM(messages: ChatMessage[], maxTokens: number = 4096): Promise<LLMResponse> {
  if (!config.llmApiKey) {
    return { success: false, content: '', error: 'LLM API key not configured' };
  }

  try {
    const response = await fetch(config.llmApiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.llmApiKey}`,
      },
      body: JSON.stringify({
        model: config.llmModel,
        messages,
        max_tokens: maxTokens,
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[LLM] API error:', response.status, errorText);
      return { success: false, content: '', error: `LLM API returned ${response.status}: ${errorText}` };
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '';

    return {
      success: true,
      content,
      usage: data.usage,
    };
  } catch (e: any) {
    console.error('[LLM] Request failed:', e.message);
    return { success: false, content: '', error: e.message };
  }
}

// AI service execution
export async function executeAIService(
  serviceId: string,
  systemPrompt: string,
  userPrompt: string
): Promise<LLMResponse> {
  const messages: ChatMessage[] = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt },
  ];

  return callLLM(messages);
}

// Fallback for when LLM is unavailable - provides meaningful demo responses
export function getFallbackResponse(serviceId: string, prompt: string): string {
  const responses: Record<string, (p: string) => string> = {
    'ai-writer': (p) => `# AI Writing Response\n\nBased on your request: "${p.slice(0, 100)}..."\n\n## Generated Content\n\nThis is a professionally crafted response to your writing request. The AI Writing Assistant has analyzed your requirements and produced content that meets professional standards.\n\n**Key Points:**\n- Clear and structured formatting\n- Professional tone maintained\n- Content tailored to your specific needs\n\n*Note: This is a demo response. In production, this would be generated by GPT-4.1.*`,

    'ai-translator': (p) => `# Translation Result\n\n**Original:** "${p.slice(0, 200)}"\n\n**Translation:** This text has been professionally translated while preserving the original meaning, context, and tone.\n\n*Note: This is a demo response. In production, real-time AI translation would be performed.*`,

    'ai-coder': (p) => `# Code Review Report\n\n## Summary\nCode review completed for the submitted code.\n\n## Findings\n\n### 🐛 Potential Issues\n1. Consider adding input validation\n2. Error handling could be improved\n\n### ⚡ Performance\n- Overall structure is good\n- Consider memoization for repeated computations\n\n### 🔒 Security\n- No critical vulnerabilities detected\n- Recommend sanitizing user inputs\n\n### ✅ Best Practices\n- Code follows consistent formatting\n- Variable naming is descriptive\n\n*Note: This is a demo response.*`,

    'ai-analyst': (p) => `# Data Analysis Report\n\n## Key Insights\n\n1. **Trend Analysis**: Positive growth trajectory observed\n2. **Anomaly Detection**: No significant outliers detected\n3. **Correlation**: Strong correlation between key variables\n\n## Recommendations\n- Monitor key metrics weekly\n- Investigate the Q2 dip further\n- Consider A/B testing for optimization\n\n*Note: This is a demo response.*`,

    'ai-summarizer': (p) => `# Summary\n\n**Key Points:**\n- The text discusses: "${p.slice(0, 80)}..."\n- Main argument centers on the primary topic\n- Supporting evidence is provided through examples\n\n**Conclusion:** The content effectively conveys its message with clear structure.\n\n*Note: This is a demo response.*`,
  };

  const handler = responses[serviceId] || responses['ai-writer'];
  return handler(prompt);
}
